# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            La tanière de papier
tagline:          'Nouvelles et textes courts'
description:      'Nouvelles et textes courts célébrant l'imaginaire par Alice Katovar'
url:              http://latanieredepapier.com
baseurl:          /

paginate: 10

excerpt_separator: <!--more-->

gems: 
 - jekyll-paginate
 - kramdown
