# Dependencies
markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            La tanière de papier
tagline:          'Nouvelles d''autres mondes'
description:      'Nouvelles d''autres mondes'
url:              http://latanieredepapier.com
baseurl:          /

paginate: 10

excerpt_separator: <!--more-->

gems: 
 - jekyll-paginate
 - kramdown
